name: Mindustry Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ios-comp:
   runs-on: macos-13
   steps:
     - uses: actions/checkout@v4
     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
          distribution: "temurin"
          java-version: 17

     - name: Setup Android SDK
       uses: android-actions/setup-android@v3
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1.4.1
       with:
          xcode-version: 14.3.1
    
     - name: Build
       run: |
          git clone --depth=1 --recurse-submodules https://github.com/anuken/mindustry
          cd mindustry
          chmod +x ./gradlew
          ./gradlew pack
          ./gradlew --stacktrace :ios:deploy -Probovm.iosSkipSigning=true
     - uses: actions/upload-artifact@v4
       with:
        name: mindustry
        path: mindustry/ios/build/robovm/
