name: Mindustry Compiler

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  ios-comp:
   runs-on: macos-13
   steps:
     - uses: actions/checkout@v4
     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
          distribution: "graalvm"
          java-version: 17

     - name: Setup Android SDK
       uses: android-actions/setup-android@v3
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1.4.1
       with:
          xcode-version: 14.3.1
     - name: Set env
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

     - name: Get dependencies/Arc natives for iOS
       run : |
         brew install gnu-sed
         mkdir -p Arc/natives
         wget https://github.com/sonphantrung/Arc/releases/download/ios-natives/arccoreios.zip
         unzip arccoreios.zip -d Arc/natives
    
     - name: Build
       run: |
          git clone --depth=1 --recurse-submodules https://github.com/anuken/mindustry
          cd mindustry
          gsed -i 's/io.anuke.mindustry/io.anuke.mindustry.be/g' ios/build.gradle
          gsed -i "s/Mindustry/Mindustry BE/g" ios/build.gradle
          chmod +x ./gradlew
          ./gradlew pack -PnoLocalArc=true
          ./gradlew --stacktrace :ios:deploy -Probovm.iosSkipSigning=true -Pbuildversion=${RELEASE_VERSION} -PversionType=bleeding-edge -PnoLocalArc=true
     - uses: actions/upload-artifact@v4
       with:
        name: mindustry
        path: mindustry/ios/build/robovm/IOSLauncher.ipa
